#!/bin/bash

killall rviz

#PARAMETERS CFEAR-3
export cost_type="P2P"
export submap_scan_size="4"
export registered_min_keyframe_dist="1.5"
export res="3"
export kstrong="40"
export zmin="60"
export weight_option="4"
export weight_intensity="true"

# CFEAR-2
#export cost_type="P2L"
#export submap_scan_size="3"
#export registered_min_keyframe_dist="1.5"
#export res="3"
#export kstrong="15"
#export zmin="70"
#export weight_intensity="true"


# CFEAR-1
#export cost_type="P2L"
#export submap_scan_size="2"
#export registered_min_keyframe_dist="0" # CHANGE THIS to 1.5!!!!!!!!!!!
#export res="3"
#export kstrong="12"
#export zmin="70"
#export weight_option="4"
#export weight_intensity="true"

# OTHER PARAMETERS #
export range_resolution="0.0595238"
export radar_ccw="true" #False for oxford, otherwise true
export soft_constraint="false"
export disable_compensate="false"
export dataset="Mulran"


export save_ROC="true"
export covar_sampling="--covar_sampling false"
export disable_training="--disable_training true"


current_date=`date '+%Y-%m-%d_%H-%M'`
EVALUATION_description="cfear-3"
BAG_BASE_PATH="${BAG_LOCATION}/Mulran" #Change this to the directory where you have the bag files
KITTI_DIR=`rospack find kitti-odom-eval`

export EVALUATION_sequence="KAIST01 KAIST02 KAIST03 DCC01 DCC02 DCC03 Riverside01 Riverside02 Riverside03"

EVALUATION_sequence_arr1=($EVALUATION_sequence)
for seq in "${EVALUATION_sequence_arr1[@]}"
do
  EVAL_BASE_DIR="${BAG_LOCATION}/TBV_Eval/Mulran/${seq}"
  est_dir="${EVAL_BASE_DIR}/est/"
  gt_dir="${EVAL_BASE_DIR}/gt/"
  training_dir="${EVAL_BASE_DIR}/training/"
  radar_dir="${EVAL_BASE_DIR}/radar/"
  mkdir -p "${est_dir}"
  mkdir -p "${gt_dir}"
  mkdir -p "${training_dir}"
  mkdir -p "${radar_dir}"
  BAG_FILE_PATH="${BAG_BASE_PATH}/${seq}/radar/${seq}.bag"
  echo "${BAG_FILE_PATH}"

  pars="--range-res ${range_resolution} --sequence ${seq} --radar_ccw ${radar_ccw} --disable_compensate ${disable_compensate} --cost_type ${cost_type} --submap_scan_size ${submap_scan_size} --registered_min_keyframe_dist ${registered_min_keyframe_dist} --res ${res} --k_strongest ${kstrong} --bag_path ${BAG_FILE_PATH} --est_directory ${est_dir} --gt_directory ${gt_dir} --training_directory ${training_dir} --radar_directory ${radar_dir} --job_nr 1 --z-min ${zmin} --loss_type ${LOSS_TYPE} --loss_limit ${LOSS_LIMIT}  --weight_intensity ${weight_intensity} --method ${EVALUATION_description} --weight_option ${weight_option} --dataset ${dataset} --store_graph true --save_radar_img false --save_ROC ${save_ROC}  ${covar_sampling} ${disable_training}"
  echo "|||||Estimating odometry with parameters: ${pars}||||"
  rosrun tbv_slam odometry_training_node ${pars} #>/dev/null
  python3 $KITTI_DIR/python/eval_odom.py --dir ${EVAL_BASE_DIR} --align 6dof --force yes >/dev/null 
done
